// Code generated by github.com/0-mqix/packed; DO NOT EDIT.

package packed

import (
	"encoding/binary"
	"unsafe"

	"github.com/0-Mqix/packed"
	"github.com/0-Mqix/packed/internal/test/types"
)

var (
	// packed.Int16Converter
	c0 = &packed.Int16Converter{}
	// packed.Int32Converter
	c1 = &packed.Int32Converter{}
	// packed.Int64Converter
	c2 = &packed.Int64Converter{}
	// packed.Int8Converter
	c3 = &packed.Int8Converter{}
	// packed.StringConverter length: 1
	c4 = &packed.StringConverter{Length: 1}
	// packed.Uint8Converter
	c5 = &packed.Uint8Converter{}
	// packed.Uint16Converter
	c6 = &packed.Uint16Converter{}
	// packed.Uint32Converter
	c7 = &packed.Uint32Converter{}
	// types.ExampleBitsTypeConverter
	c8 = &types.ExampleBitsTypeConverter{}
	// types.ExampleConverter
	c9 = &types.ExampleConverter{}
)

type A struct {
	A uint8  `json:"a" xml:"a"`
	B uint16 `json:"b" xml:"b"`
	C uint32 `json:"c" xml:"c"`
	D int64  `json:"d" xml:"d"`
	E int8   `json:"e" xml:"e"`
	F int8   `json:"f" xml:"f"`
	G types.ExampleTypeInterface
}

func (reciever *A) Size() int {
	return 18
}

func (reciever *A) ToBytes(bytes []byte, index int) {
	c5.ToBytesLittleEndian(&reciever.A, bytes, index+0)
	c6.ToBytesLittleEndian(&reciever.B, bytes, index+1)
	c7.ToBytesLittleEndian(&reciever.C, bytes, index+3)
	c2.ToBytesLittleEndian(&reciever.D, bytes, index+7)
	c3.ToBytesLittleEndian(&reciever.E, bytes, index+15)
	c3.ToBytesLittleEndian(&reciever.F, bytes, index+16)
	reciever.G.ToBytesLittleEndian(bytes, index+17)
}

func (reciever *A) FromBytes(bytes []byte, index int) {
	c5.FromBytesLittleEndian(&reciever.A, bytes, index+0)
	c6.FromBytesLittleEndian(&reciever.B, bytes, index+1)
	c7.FromBytesLittleEndian(&reciever.C, bytes, index+3)
	c2.FromBytesLittleEndian(&reciever.D, bytes, index+7)
	c3.FromBytesLittleEndian(&reciever.E, bytes, index+15)
	c3.FromBytesLittleEndian(&reciever.F, bytes, index+16)
	reciever.G.FromBytesLittleEndian(bytes, index+17)
}

func (r *A) GetA() int { return int(r.A) }
func (r *A) GetB() int { return int(r.B) }
func (r *A) GetC() int { return int(r.C) }
func (r *A) GetD() int { return int(r.D) }
func (r *A) GetE() int { return int(r.E) }
func (r *A) GetF() int { return int(r.F) }

type B struct {
	A uint8  `json:"a" xml:"a"`
	B uint16 `json:"b" xml:"b"`
	C uint32 `json:"c" xml:"c"`
	D int64  `json:"d" xml:"d"`
	E int8   `json:"e" xml:"e"`
	F bool   `json:"f" xml:"f"`
	G int8   `json:"g" xml:"g"`
}

func (reciever *B) Size() int {
	return 9
}

func (reciever *B) ToBytes(bytes []byte, index int) {
	var b0 uint64
	b0 |= (uint64(reciever.A) & 0xF) << 60
	b0 |= (uint64(reciever.B) & 0x3FF) << 50
	b0 |= (uint64(reciever.C) & 0xFFFFF) << 30
	b0 |= (uint64(reciever.D) & 0x3FFFFFFF)
	binary.BigEndian.PutUint64(bytes[index+0+0:index+0+8], uint64(b0))
	var b1 uint64
	b1 |= (uint64(reciever.E) & 0xF) << 4
	b1 |= (uint64(*(*uint8)(unsafe.Pointer(&reciever.F))) & 1) << 3
	b1 |= (uint64(reciever.G) & 0x7)
	bytes[index+8+0] = byte(b1)
}

func (reciever *B) FromBytes(bytes []byte, index int) {
	var b0 uint64
	b0 |= uint64(bytes[index+0+7]) << 0
	b0 |= uint64(bytes[index+0+6]) << 8
	b0 |= uint64(bytes[index+0+5]) << 16
	b0 |= uint64(bytes[index+0+4]) << 24
	b0 |= uint64(bytes[index+0+3]) << 32
	b0 |= uint64(bytes[index+0+2]) << 40
	b0 |= uint64(bytes[index+0+1]) << 48
	b0 |= uint64(bytes[index+0+0]) << 56
	reciever.A = uint8(uint64((b0 >> 60) & 0xF))
	reciever.B = uint16(uint64((b0 >> 50) & 0x3FF))
	reciever.C = uint32(uint64((b0 >> 30) & 0xFFFFF))
	reciever.D = int64((((b0 >> 0) & 0x3FFFFFFF) ^ (1 << 29)) - (1 << 29))
	var b1 uint64
	b1 |= uint64(bytes[index+8+0]) << 0
	reciever.E = int8((((b1 >> 4) & 0xF) ^ (1 << 3)) - (1 << 3))
	reciever.F = ((b1 >> 3) & 0x1) != 0
	reciever.G = int8((((b1 >> 0) & 0x7) ^ (1 << 2)) - (1 << 2))
}

func (r *B) GetA() int  { return int(r.A) }
func (r *B) GetB() int  { return int(r.B) }
func (r *B) GetC() int  { return int(r.C) }
func (r *B) GetD() int  { return int(r.D) }
func (r *B) GetE() int  { return int(r.E) }
func (r *B) GetF() bool { return r.F }
func (r *B) GetG() int  { return int(r.G) }

type C struct {
	A uint8
	B uint16
	C uint32
	D int64
	E int8
	F bool
	G int8
}

func (reciever *C) Size() int {
	return 9
}

func (reciever *C) ToBytes(bytes []byte, index int) {
	var b0 uint64
	b0 |= (uint64(reciever.A) & 0xF)
	b0 |= (uint64(reciever.B) & 0x3FF) << 4
	b0 |= (uint64(reciever.C) & 0xFFFFF) << 14
	b0 |= (uint64(reciever.D) & 0x3FFFFFFF) << 34
	binary.LittleEndian.PutUint64(bytes[index+0+0:index+0+8], uint64(b0))
	var b1 uint64
	b1 |= (uint64(reciever.E) & 0xF)
	b1 |= (uint64(*(*uint8)(unsafe.Pointer(&reciever.F))) & 1) << 4
	b1 |= (uint64(reciever.G) & 0x7) << 5
	bytes[index+8+0] = byte(b1)
}

func (reciever *C) FromBytes(bytes []byte, index int) {
	var b0 uint64
	b0 |= uint64(bytes[index+0+0]) << 0
	b0 |= uint64(bytes[index+0+1]) << 8
	b0 |= uint64(bytes[index+0+2]) << 16
	b0 |= uint64(bytes[index+0+3]) << 24
	b0 |= uint64(bytes[index+0+4]) << 32
	b0 |= uint64(bytes[index+0+5]) << 40
	b0 |= uint64(bytes[index+0+6]) << 48
	b0 |= uint64(bytes[index+0+7]) << 56
	reciever.A = uint8(uint64((b0 >> 0) & 0xF))
	reciever.B = uint16(uint64((b0 >> 4) & 0x3FF))
	reciever.C = uint32(uint64((b0 >> 14) & 0xFFFFF))
	reciever.D = int64((((b0 >> 34) & 0x3FFFFFFF) ^ (1 << 29)) - (1 << 29))
	var b1 uint64
	b1 |= uint64(bytes[index+8+0]) << 0
	reciever.E = int8((((b1 >> 0) & 0xF) ^ (1 << 3)) - (1 << 3))
	reciever.F = ((b1 >> 4) & 0x1) != 0
	reciever.G = int8((((b1 >> 5) & 0x7) ^ (1 << 2)) - (1 << 2))
}

func (r *C) GetA() int  { return int(r.A) }
func (r *C) GetB() int  { return int(r.B) }
func (r *C) GetC() int  { return int(r.C) }
func (r *C) GetD() int  { return int(r.D) }
func (r *C) GetE() int  { return int(r.E) }
func (r *C) GetF() bool { return r.F }
func (r *C) GetG() int  { return int(r.G) }

type D struct {
	A B
	B C
}

func (reciever *D) Size() int {
	return 18
}

func (reciever *D) ToBytes(bytes []byte, index int) {
	var b0 uint64
	b0 |= (uint64(reciever.A.A) & 0xF)
	b0 |= (uint64(reciever.A.B) & 0x3FF) << 4
	b0 |= (uint64(reciever.A.C) & 0xFFFFF) << 14
	b0 |= (uint64(reciever.A.D) & 0x3FFFFFFF) << 34
	binary.LittleEndian.PutUint64(bytes[index+0+0:index+0+8], uint64(b0))
	var b1 uint64
	b1 |= (uint64(reciever.A.E) & 0xF)
	b1 |= (uint64(*(*uint8)(unsafe.Pointer(&reciever.A.F))) & 1) << 4
	b1 |= (uint64(reciever.A.G) & 0x7) << 5
	bytes[index+8+0] = byte(b1)
	var b2 uint64
	b2 |= (uint64(reciever.B.A) & 0xF)
	b2 |= (uint64(reciever.B.B) & 0x3FF) << 4
	b2 |= (uint64(reciever.B.C) & 0xFFFFF) << 14
	b2 |= (uint64(reciever.B.D) & 0x3FFFFFFF) << 34
	binary.LittleEndian.PutUint64(bytes[index+9+0:index+9+8], uint64(b2))
	var b3 uint64
	b3 |= (uint64(reciever.B.E) & 0xF)
	b3 |= (uint64(*(*uint8)(unsafe.Pointer(&reciever.B.F))) & 1) << 4
	b3 |= (uint64(reciever.B.G) & 0x7) << 5
	bytes[index+17+0] = byte(b3)
}

func (reciever *D) FromBytes(bytes []byte, index int) {
	var b0 uint64
	b0 |= uint64(bytes[index+0+0]) << 0
	b0 |= uint64(bytes[index+0+1]) << 8
	b0 |= uint64(bytes[index+0+2]) << 16
	b0 |= uint64(bytes[index+0+3]) << 24
	b0 |= uint64(bytes[index+0+4]) << 32
	b0 |= uint64(bytes[index+0+5]) << 40
	b0 |= uint64(bytes[index+0+6]) << 48
	b0 |= uint64(bytes[index+0+7]) << 56
	reciever.A.A = uint8(uint64((b0 >> 0) & 0xF))
	reciever.A.B = uint16(uint64((b0 >> 4) & 0x3FF))
	reciever.A.C = uint32(uint64((b0 >> 14) & 0xFFFFF))
	reciever.A.D = int64((((b0 >> 34) & 0x3FFFFFFF) ^ (1 << 29)) - (1 << 29))
	var b1 uint64
	b1 |= uint64(bytes[index+8+0]) << 0
	reciever.A.E = int8((((b1 >> 0) & 0xF) ^ (1 << 3)) - (1 << 3))
	reciever.A.F = ((b1 >> 4) & 0x1) != 0
	reciever.A.G = int8((((b1 >> 5) & 0x7) ^ (1 << 2)) - (1 << 2))
	var b2 uint64
	b2 |= uint64(bytes[index+9+0]) << 0
	b2 |= uint64(bytes[index+9+1]) << 8
	b2 |= uint64(bytes[index+9+2]) << 16
	b2 |= uint64(bytes[index+9+3]) << 24
	b2 |= uint64(bytes[index+9+4]) << 32
	b2 |= uint64(bytes[index+9+5]) << 40
	b2 |= uint64(bytes[index+9+6]) << 48
	b2 |= uint64(bytes[index+9+7]) << 56
	reciever.B.A = uint8(uint64((b2 >> 0) & 0xF))
	reciever.B.B = uint16(uint64((b2 >> 4) & 0x3FF))
	reciever.B.C = uint32(uint64((b2 >> 14) & 0xFFFFF))
	reciever.B.D = int64((((b2 >> 34) & 0x3FFFFFFF) ^ (1 << 29)) - (1 << 29))
	var b3 uint64
	b3 |= uint64(bytes[index+17+0]) << 0
	reciever.B.E = int8((((b3 >> 0) & 0xF) ^ (1 << 3)) - (1 << 3))
	reciever.B.F = ((b3 >> 4) & 0x1) != 0
	reciever.B.G = int8((((b3 >> 5) & 0x7) ^ (1 << 2)) - (1 << 2))
}

type E struct {
	A [2]D
}

func (reciever *E) Size() int {
	return 36
}

func (reciever *E) ToBytes(bytes []byte, index int) {
	o0 := index + 0
	for i0 := 0; i0 < 2; i0++ {
		var b0 uint64
		b0 |= (uint64(reciever.A[i0].A.A) & 0xF)
		b0 |= (uint64(reciever.A[i0].A.B) & 0x3FF) << 4
		b0 |= (uint64(reciever.A[i0].A.C) & 0xFFFFF) << 14
		b0 |= (uint64(reciever.A[i0].A.D) & 0x3FFFFFFF) << 34
		binary.LittleEndian.PutUint64(bytes[o0+0:o0+8], uint64(b0))
		o0 += 8
		var b1 uint64
		b1 |= (uint64(reciever.A[i0].A.E) & 0xF)
		b1 |= (uint64(*(*uint8)(unsafe.Pointer(&reciever.A[i0].A.F))) & 1) << 4
		b1 |= (uint64(reciever.A[i0].A.G) & 0x7) << 5
		bytes[o0+0] = byte(b1)
		o0 += 1
		var b2 uint64
		b2 |= (uint64(reciever.A[i0].B.A) & 0xF)
		b2 |= (uint64(reciever.A[i0].B.B) & 0x3FF) << 4
		b2 |= (uint64(reciever.A[i0].B.C) & 0xFFFFF) << 14
		b2 |= (uint64(reciever.A[i0].B.D) & 0x3FFFFFFF) << 34
		binary.LittleEndian.PutUint64(bytes[o0+0:o0+8], uint64(b2))
		o0 += 8
		var b3 uint64
		b3 |= (uint64(reciever.A[i0].B.E) & 0xF)
		b3 |= (uint64(*(*uint8)(unsafe.Pointer(&reciever.A[i0].B.F))) & 1) << 4
		b3 |= (uint64(reciever.A[i0].B.G) & 0x7) << 5
		bytes[o0+0] = byte(b3)
		o0 += 1
	}
}

func (reciever *E) FromBytes(bytes []byte, index int) {
	o0 := index + 0
	for i0 := 0; i0 < 2; i0++ {
		var b0 uint64
		b0 |= uint64(bytes[o0+0]) << 0
		b0 |= uint64(bytes[o0+1]) << 8
		b0 |= uint64(bytes[o0+2]) << 16
		b0 |= uint64(bytes[o0+3]) << 24
		b0 |= uint64(bytes[o0+4]) << 32
		b0 |= uint64(bytes[o0+5]) << 40
		b0 |= uint64(bytes[o0+6]) << 48
		b0 |= uint64(bytes[o0+7]) << 56
		reciever.A[i0].A.A = uint8(uint64((b0 >> 0) & 0xF))
		reciever.A[i0].A.B = uint16(uint64((b0 >> 4) & 0x3FF))
		reciever.A[i0].A.C = uint32(uint64((b0 >> 14) & 0xFFFFF))
		reciever.A[i0].A.D = int64((((b0 >> 34) & 0x3FFFFFFF) ^ (1 << 29)) - (1 << 29))
		o0 += 8
		var b1 uint64
		b1 |= uint64(bytes[o0+0]) << 0
		reciever.A[i0].A.E = int8((((b1 >> 0) & 0xF) ^ (1 << 3)) - (1 << 3))
		reciever.A[i0].A.F = ((b1 >> 4) & 0x1) != 0
		reciever.A[i0].A.G = int8((((b1 >> 5) & 0x7) ^ (1 << 2)) - (1 << 2))
		o0 += 1
		var b2 uint64
		b2 |= uint64(bytes[o0+0]) << 0
		b2 |= uint64(bytes[o0+1]) << 8
		b2 |= uint64(bytes[o0+2]) << 16
		b2 |= uint64(bytes[o0+3]) << 24
		b2 |= uint64(bytes[o0+4]) << 32
		b2 |= uint64(bytes[o0+5]) << 40
		b2 |= uint64(bytes[o0+6]) << 48
		b2 |= uint64(bytes[o0+7]) << 56
		reciever.A[i0].B.A = uint8(uint64((b2 >> 0) & 0xF))
		reciever.A[i0].B.B = uint16(uint64((b2 >> 4) & 0x3FF))
		reciever.A[i0].B.C = uint32(uint64((b2 >> 14) & 0xFFFFF))
		reciever.A[i0].B.D = int64((((b2 >> 34) & 0x3FFFFFFF) ^ (1 << 29)) - (1 << 29))
		o0 += 8
		var b3 uint64
		b3 |= uint64(bytes[o0+0]) << 0
		reciever.A[i0].B.E = int8((((b3 >> 0) & 0xF) ^ (1 << 3)) - (1 << 3))
		reciever.A[i0].B.F = ((b3 >> 4) & 0x1) != 0
		reciever.A[i0].B.G = int8((((b3 >> 5) & 0x7) ^ (1 << 2)) - (1 << 2))
		o0 += 1
	}
}

type F struct {
	A [2][2][2]types.ExampleTypeInterface
}

func (reciever *F) Size() int {
	return 8
}

func (reciever *F) ToBytes(bytes []byte, index int) {
	o0 := index + 0
	for i0 := 0; i0 < 2; i0++ {
		for i1 := 0; i1 < 2; i1++ {
			for i2 := 0; i2 < 2; i2++ {
				reciever.A[i0][i1][i2].ToBytesLittleEndian(bytes, o0)
				o0 += 1
			}
		}
	}
}

func (reciever *F) FromBytes(bytes []byte, index int) {
	o0 := index + 0
	for i0 := 0; i0 < 2; i0++ {
		for i1 := 0; i1 < 2; i1++ {
			for i2 := 0; i2 < 2; i2++ {
				reciever.A[i0][i1][i2].FromBytesLittleEndian(bytes, o0)
				o0 += 1
			}
		}
	}
}

type G struct {
	A [2][2][2]types.ExampleRecieverType
}

func (reciever *G) Size() int {
	return 8
}

func (reciever *G) ToBytes(bytes []byte, index int) {
	o0 := index + 0
	for i0 := 0; i0 < 2; i0++ {
		for i1 := 0; i1 < 2; i1++ {
			for i2 := 0; i2 < 2; i2++ {
				c9.ToBytesLittleEndian(&reciever.A[i0][i1][i2], bytes, o0)
				o0 += 1
			}
		}
	}
}

func (reciever *G) FromBytes(bytes []byte, index int) {
	o0 := index + 0
	for i0 := 0; i0 < 2; i0++ {
		for i1 := 0; i1 < 2; i1++ {
			for i2 := 0; i2 < 2; i2++ {
				c9.FromBytesLittleEndian(&reciever.A[i0][i1][i2], bytes, o0)
				o0 += 1
			}
		}
	}
}

type H struct {
	A types.ExampleEnum
}

func (reciever *H) Size() int {
	return 2
}

func (reciever *H) ToBytes(bytes []byte, index int) {
	var r0 int16
	r0 = int16(reciever.A)
	c0.ToBytesBigEndian(&r0, bytes, index+0)
}

func (reciever *H) FromBytes(bytes []byte, index int) {
	var r0 int16
	c0.FromBytesBigEndian(&r0, bytes, index+0)
	reciever.A = types.ExampleEnum(r0)
}

func (r *H) GetA() int { return int(r.A) }

type I struct {
	A types.ExampleEnum
	B [2]types.ExampleEnum
	C [2]H
	D types.ExampleEnumString
}

func (reciever *I) Size() int {
	return 11
}

func (reciever *I) ToBytes(bytes []byte, index int) {
	var r0 int32
	var r1 int8
	var r2 int16
	var r3 string
	r0 = int32(reciever.A)
	c1.ToBytesLittleEndian(&r0, bytes, index+0)
	o4 := index + 4
	for i0 := 0; i0 < 2; i0++ {
		r1 = int8(reciever.B[i0])
		c3.ToBytesLittleEndian(&r1, bytes, o4)
		o4 += 1
	}
	o6 := index + 6
	for i0 := 0; i0 < 2; i0++ {
		r2 = int16(reciever.C[i0].A)
		c0.ToBytesBigEndian(&r2, bytes, o6)
		o6 += 2
	}
	r3 = string(reciever.D)
	c4.ToBytesLittleEndian(&r3, bytes, index+10)
}

func (reciever *I) FromBytes(bytes []byte, index int) {
	var r0 int32
	var r1 int8
	var r2 int16
	var r3 string
	c1.FromBytesLittleEndian(&r0, bytes, index+0)
	reciever.A = types.ExampleEnum(r0)
	o4 := index + 4
	for i0 := 0; i0 < 2; i0++ {
		c3.FromBytesLittleEndian(&r1, bytes, o4)
		reciever.B[i0] = types.ExampleEnum(r1)
		o4 += 1
	}
	o6 := index + 6
	for i0 := 0; i0 < 2; i0++ {
		c0.FromBytesBigEndian(&r2, bytes, o6)
		reciever.C[i0].A = types.ExampleEnum(r2)
		o6 += 2
	}
	c4.FromBytesLittleEndian(&r3, bytes, index+10)
	reciever.D = types.ExampleEnumString(r3)
}

func (r *I) GetA() int { return int(r.A) }

type J struct {
	A uint8
	B types.ExampleBitsType
}

func (reciever *J) Size() int {
	return 2
}

func (reciever *J) ToBytes(bytes []byte, index int) {
	var b0 uint64
	b0 |= (uint64(reciever.A) & 0x3F)
	b0 |= (uint64(reciever.B.Integer()) & 0x3FF) << 6
	binary.LittleEndian.PutUint16(bytes[index+0+0:index+0+2], uint16(b0))
}

func (reciever *J) FromBytes(bytes []byte, index int) {
	var b0 uint64
	b0 |= uint64(bytes[index+0+0]) << 0
	b0 |= uint64(bytes[index+0+1]) << 8
	reciever.A = uint8(uint64((b0 >> 0) & 0x3F))
	reciever.B.Set(uint16(uint64((b0 >> 6) & 0x3FF)))
}

func (r *J) GetA() int { return int(r.A) }

type K struct {
	A uint8
	B types.ExampleBitsType
}

func (reciever *K) Size() int {
	return 2
}

func (reciever *K) ToBytes(bytes []byte, index int) {
	var b0 uint64
	b0 |= (uint64(reciever.A) & 0x3F) << 10
	b0 |= (uint64(reciever.B.Integer()) & 0x3FF)
	binary.BigEndian.PutUint16(bytes[index+0+0:index+0+2], uint16(b0))
}

func (reciever *K) FromBytes(bytes []byte, index int) {
	var b0 uint64
	b0 |= uint64(bytes[index+0+1]) << 0
	b0 |= uint64(bytes[index+0+0]) << 8
	reciever.A = uint8(uint64((b0 >> 10) & 0x3F))
	reciever.B.Set(uint16(uint64((b0 >> 0) & 0x3FF)))
}

func (r *K) GetA() int { return int(r.A) }

type L struct {
	A uint8
	B [10]bool
}

func (reciever *L) Size() int {
	return 2
}

func (reciever *L) ToBytes(bytes []byte, index int) {
	var b0 uint64
	b0 |= (uint64(reciever.A) & 0xF)
	b0 |= (uint64(c8.Integer(&reciever.B)) & 0x3FF) << 4
	binary.LittleEndian.PutUint16(bytes[index+0+0:index+0+2], uint16(b0))
}

func (reciever *L) FromBytes(bytes []byte, index int) {
	var b0 uint64
	b0 |= uint64(bytes[index+0+0]) << 0
	b0 |= uint64(bytes[index+0+1]) << 8
	reciever.A = uint8(uint64((b0 >> 0) & 0xF))
	c8.Set(&reciever.B, uint16(uint64((b0>>4)&0x3FF)))
}

func (r *L) GetA() int { return int(r.A) }

type M struct {
	A [2]L
	B [2]K
}

func (reciever *M) Size() int {
	return 8
}

func (reciever *M) ToBytes(bytes []byte, index int) {
	o0 := index + 0
	for i0 := 0; i0 < 2; i0++ {
		var b0 uint64
		b0 |= (uint64(reciever.A[i0].A) & 0xF)
		b0 |= (uint64(c8.Integer(&reciever.A[i0].B)) & 0x3FF) << 4
		binary.LittleEndian.PutUint16(bytes[o0+0:o0+2], uint16(b0))
		o0 += 2
	}
	o4 := index + 4
	for i0 := 0; i0 < 2; i0++ {
		var b0 uint64
		b0 |= (uint64(reciever.B[i0].A) & 0x3F) << 10
		b0 |= (uint64(reciever.B[i0].B.Integer()) & 0x3FF)
		binary.BigEndian.PutUint16(bytes[o4+0:o4+2], uint16(b0))
		o4 += 2
	}
}

func (reciever *M) FromBytes(bytes []byte, index int) {
	o0 := index + 0
	for i0 := 0; i0 < 2; i0++ {
		var b0 uint64
		b0 |= uint64(bytes[o0+0]) << 0
		b0 |= uint64(bytes[o0+1]) << 8
		reciever.A[i0].A = uint8(uint64((b0 >> 0) & 0xF))
		c8.Set(&reciever.A[i0].B, uint16(uint64((b0>>4)&0x3FF)))
		o0 += 2
	}
	o4 := index + 4
	for i0 := 0; i0 < 2; i0++ {
		var b0 uint64
		b0 |= uint64(bytes[o4+1]) << 0
		b0 |= uint64(bytes[o4+0]) << 8
		reciever.B[i0].A = uint8(uint64((b0 >> 10) & 0x3F))
		reciever.B[i0].B.Set(uint16(uint64((b0 >> 0) & 0x3FF)))
		o4 += 2
	}
}

type N struct {
	A uint8
	B int8
}

func (reciever *N) Size() int {
	return 1
}

func (reciever *N) ToBytes(bytes []byte, index int) {
	var b0 uint64
	b0 |= (uint64(reciever.A) & 0xF) << 4
	b0 |= (uint64(reciever.B) & 0x7) << 1
	bytes[index+0+0] = byte(b0)
}

func (reciever *N) FromBytes(bytes []byte, index int) {
	var b0 uint64
	b0 |= uint64(bytes[index+0+0]) << 0
	reciever.A = uint8(uint64((b0 >> 4) & 0xF))
	reciever.B = int8((((b0 >> 1) & 0x7) ^ (1 << 2)) - (1 << 2))
}

func (r *N) GetA() int { return int(r.A) }
func (r *N) GetB() int { return int(r.B) }

type O struct {
	A uint32
	B uint64
	C int16
	D uint8
	E bool
}

func (reciever *O) Size() int {
	return 10
}

func (reciever *O) ToBytes(bytes []byte, index int) {
	var b0 uint64
	b0 |= (uint64(reciever.A) & 0xFFFFF)
	b0 |= (uint64(reciever.B) & 0x7FFFFFFFF) << 20
	s0_2 := uint64(reciever.C) & 0x1FFF
	b0 |= (s0_2 & 0x1FF) << 55
	binary.LittleEndian.PutUint64(bytes[index+0+0:index+0+8], uint64(b0))
	var b1 uint64
	b1 |= ((s0_2 >> 9) & 0xF)
	b1 |= (uint64(reciever.D) & 0x7F) << 4
	b1 |= (uint64(*(*uint8)(unsafe.Pointer(&reciever.E))) & 1) << 11
	binary.LittleEndian.PutUint16(bytes[index+8+0:index+8+2], uint16(b1))
}

func (reciever *O) FromBytes(bytes []byte, index int) {
	var b0 uint64
	b0 |= uint64(bytes[index+0+0]) << 0
	b0 |= uint64(bytes[index+0+1]) << 8
	b0 |= uint64(bytes[index+0+2]) << 16
	b0 |= uint64(bytes[index+0+3]) << 24
	b0 |= uint64(bytes[index+0+4]) << 32
	b0 |= uint64(bytes[index+0+5]) << 40
	b0 |= uint64(bytes[index+0+6]) << 48
	b0 |= uint64(bytes[index+0+7]) << 56
	reciever.A = uint32(uint64((b0 >> 0) & 0xFFFFF))
	reciever.B = uint64(uint64((b0 >> 20) & 0x7FFFFFFFF))
	var b1 uint64
	b1 |= uint64(bytes[index+8+0]) << 0
	b1 |= uint64(bytes[index+8+1]) << 8
	s0_2 := ((b0 >> 55) & 0x1FF) | (((b1 >> 0) & 0xF) << 9)
	reciever.C = int16(((s0_2) ^ (1 << 12)) - (1 << 12))
	reciever.D = uint8(uint64((b1 >> 4) & 0x7F))
	reciever.E = ((b1 >> 11) & 0x1) != 0
}

func (r *O) GetA() int  { return int(r.A) }
func (r *O) GetB() int  { return int(r.B) }
func (r *O) GetC() int  { return int(r.C) }
func (r *O) GetD() int  { return int(r.D) }
func (r *O) GetE() bool { return r.E }

type P struct {
	A uint32
	B uint64
	C int16
	D uint8
	E bool
}

func (reciever *P) Size() int {
	return 10
}

func (reciever *P) ToBytes(bytes []byte, index int) {
	var b0 uint64
	b0 |= (uint64(reciever.A) & 0xFFFFF) << 44
	b0 |= (uint64(reciever.B) & 0x7FFFFFFFF) << 9
	s0_2 := uint64(reciever.C) & 0x1FFF
	b0 |= ((s0_2 >> 4) & 0x1FF)
	binary.BigEndian.PutUint64(bytes[index+0+0:index+0+8], uint64(b0))
	var b1 uint64
	b1 |= (s0_2 & 0xF) << 12
	b1 |= (uint64(reciever.D) & 0x7F) << 5
	b1 |= (uint64(*(*uint8)(unsafe.Pointer(&reciever.E))) & 1) << 4
	binary.BigEndian.PutUint16(bytes[index+8+0:index+8+2], uint16(b1))
}

func (reciever *P) FromBytes(bytes []byte, index int) {
	var b0 uint64
	b0 |= uint64(bytes[index+0+7]) << 0
	b0 |= uint64(bytes[index+0+6]) << 8
	b0 |= uint64(bytes[index+0+5]) << 16
	b0 |= uint64(bytes[index+0+4]) << 24
	b0 |= uint64(bytes[index+0+3]) << 32
	b0 |= uint64(bytes[index+0+2]) << 40
	b0 |= uint64(bytes[index+0+1]) << 48
	b0 |= uint64(bytes[index+0+0]) << 56
	reciever.A = uint32(uint64((b0 >> 44) & 0xFFFFF))
	reciever.B = uint64(uint64((b0 >> 9) & 0x7FFFFFFFF))
	var b1 uint64
	b1 |= uint64(bytes[index+8+1]) << 0
	b1 |= uint64(bytes[index+8+0]) << 8
	s0_2 := (((b0 >> 0) & 0x1FF) << 4) | ((b1 >> 12) & 0xF)
	reciever.C = int16(((s0_2) ^ (1 << 12)) - (1 << 12))
	reciever.D = uint8(uint64((b1 >> 5) & 0x7F))
	reciever.E = ((b1 >> 4) & 0x1) != 0
}

func (r *P) GetA() int  { return int(r.A) }
func (r *P) GetB() int  { return int(r.B) }
func (r *P) GetC() int  { return int(r.C) }
func (r *P) GetD() int  { return int(r.D) }
func (r *P) GetE() bool { return r.E }

type Q struct {
	A uint64
	B uint64
	C uint64
	D int8
}

func (reciever *Q) Size() int {
	return 19
}

func (reciever *Q) ToBytes(bytes []byte, index int) {
	var b0 uint64
	b0 |= (uint64(reciever.A) & 0x3FFFFFFFFFFFF)
	s0_1 := uint64(reciever.B) & 0x3FFFFFFFFFFFF
	b0 |= (s0_1 & 0x3FFF) << 50
	binary.LittleEndian.PutUint64(bytes[index+0+0:index+0+8], uint64(b0))
	var b1 uint64
	b1 |= ((s0_1 >> 14) & 0xFFFFFFFFF)
	s0_2 := uint64(reciever.C) & 0xFFFFFFFFFF
	b1 |= (s0_2 & 0xFFFFFFF) << 36
	binary.LittleEndian.PutUint64(bytes[index+8+0:index+8+8], uint64(b1))
	var b2 uint64
	b2 |= ((s0_2 >> 28) & 0xFFF)
	b2 |= (uint64(reciever.D) & 0x1F) << 12
	binary.LittleEndian.PutUint16(bytes[index+16+0:index+16+2], uint16(b2))
	bytes[index+16+2] = byte(b2 >> 16)
}

func (reciever *Q) FromBytes(bytes []byte, index int) {
	var b0 uint64
	b0 |= uint64(bytes[index+0+0]) << 0
	b0 |= uint64(bytes[index+0+1]) << 8
	b0 |= uint64(bytes[index+0+2]) << 16
	b0 |= uint64(bytes[index+0+3]) << 24
	b0 |= uint64(bytes[index+0+4]) << 32
	b0 |= uint64(bytes[index+0+5]) << 40
	b0 |= uint64(bytes[index+0+6]) << 48
	b0 |= uint64(bytes[index+0+7]) << 56
	reciever.A = uint64(uint64((b0 >> 0) & 0x3FFFFFFFFFFFF))
	var b1 uint64
	b1 |= uint64(bytes[index+8+0]) << 0
	b1 |= uint64(bytes[index+8+1]) << 8
	b1 |= uint64(bytes[index+8+2]) << 16
	b1 |= uint64(bytes[index+8+3]) << 24
	b1 |= uint64(bytes[index+8+4]) << 32
	b1 |= uint64(bytes[index+8+5]) << 40
	b1 |= uint64(bytes[index+8+6]) << 48
	b1 |= uint64(bytes[index+8+7]) << 56
	s0_1 := ((b0 >> 50) & 0x3FFF) | (((b1 >> 0) & 0xFFFFFFFFF) << 14)
	reciever.B = uint64(uint64(s0_1))
	var b2 uint64
	b2 |= uint64(bytes[index+16+0]) << 0
	b2 |= uint64(bytes[index+16+1]) << 8
	b2 |= uint64(bytes[index+16+2]) << 16
	s0_2 := ((b1 >> 36) & 0xFFFFFFF) | (((b2 >> 0) & 0xFFF) << 28)
	reciever.C = uint64(uint64(s0_2))
	reciever.D = int8((((b2 >> 12) & 0x1F) ^ (1 << 4)) - (1 << 4))
}

func (r *Q) GetA() int { return int(r.A) }
func (r *Q) GetB() int { return int(r.B) }
func (r *Q) GetC() int { return int(r.C) }
func (r *Q) GetD() int { return int(r.D) }

type R struct {
	A uint64
	B uint64
	C uint64
	D int8
}

func (reciever *R) Size() int {
	return 19
}

func (reciever *R) ToBytes(bytes []byte, index int) {
	var b0 uint64
	b0 |= (uint64(reciever.A) & 0x3FFFFFFFFFFFF) << 14
	s0_1 := uint64(reciever.B) & 0x3FFFFFFFFFFFF
	b0 |= ((s0_1 >> 36) & 0x3FFF)
	binary.BigEndian.PutUint64(bytes[index+0+0:index+0+8], uint64(b0))
	var b1 uint64
	b1 |= (s0_1 & 0xFFFFFFFFF) << 28
	s0_2 := uint64(reciever.C) & 0xFFFFFFFFFF
	b1 |= ((s0_2 >> 12) & 0xFFFFFFF)
	binary.BigEndian.PutUint64(bytes[index+8+0:index+8+8], uint64(b1))
	var b2 uint64
	b2 |= (s0_2 & 0xFFF) << 12
	b2 |= (uint64(reciever.D) & 0x1F) << 7
	binary.BigEndian.PutUint16(bytes[index+16+1:index+16+3], uint16(b2))
	bytes[index+16+0] = byte(b2 >> 16)
}

func (reciever *R) FromBytes(bytes []byte, index int) {
	var b0 uint64
	b0 |= uint64(bytes[index+0+7]) << 0
	b0 |= uint64(bytes[index+0+6]) << 8
	b0 |= uint64(bytes[index+0+5]) << 16
	b0 |= uint64(bytes[index+0+4]) << 24
	b0 |= uint64(bytes[index+0+3]) << 32
	b0 |= uint64(bytes[index+0+2]) << 40
	b0 |= uint64(bytes[index+0+1]) << 48
	b0 |= uint64(bytes[index+0+0]) << 56
	reciever.A = uint64(uint64((b0 >> 14) & 0x3FFFFFFFFFFFF))
	var b1 uint64
	b1 |= uint64(bytes[index+8+7]) << 0
	b1 |= uint64(bytes[index+8+6]) << 8
	b1 |= uint64(bytes[index+8+5]) << 16
	b1 |= uint64(bytes[index+8+4]) << 24
	b1 |= uint64(bytes[index+8+3]) << 32
	b1 |= uint64(bytes[index+8+2]) << 40
	b1 |= uint64(bytes[index+8+1]) << 48
	b1 |= uint64(bytes[index+8+0]) << 56
	s0_1 := (((b0 >> 0) & 0x3FFF) << 36) | ((b1 >> 28) & 0xFFFFFFFFF)
	reciever.B = uint64(uint64(s0_1))
	var b2 uint64
	b2 |= uint64(bytes[index+16+2]) << 0
	b2 |= uint64(bytes[index+16+1]) << 8
	b2 |= uint64(bytes[index+16+0]) << 16
	s0_2 := (((b1 >> 0) & 0xFFFFFFF) << 12) | ((b2 >> 12) & 0xFFF)
	reciever.C = uint64(uint64(s0_2))
	reciever.D = int8((((b2 >> 7) & 0x1F) ^ (1 << 4)) - (1 << 4))
}

func (r *R) GetA() int { return int(r.A) }
func (r *R) GetB() int { return int(r.B) }
func (r *R) GetC() int { return int(r.C) }
func (r *R) GetD() int { return int(r.D) }

type S struct {
	F0  uint32
	F1  uint32
	F2  uint32
	F3  uint32
	F4  uint32
	F5  uint32
	F6  uint32
	F7  uint32
	F8  uint32
	F9  uint32
	F10 uint32
	F11 uint32
	F12 uint32
	F13 uint32
	F14 uint32
	F15 uint32
	F16 uint32
	F17 uint32
	F18 uint32
	F19 uint32
	F20 uint32
}

func (reciever *S) Size() int {
	return 10
}

func (reciever *S) ToBytes(bytes []byte, index int) {
	var b0 uint64
	b0 |= (uint64(reciever.F0) & 0x1F)
	b0 |= (uint64(reciever.F1) & 0x1F) << 5
	b0 |= (uint64(reciever.F2) & 0x1F) << 10
	b0 |= (uint64(reciever.F3) & 0x1F) << 15
	b0 |= (uint64(reciever.F4) & 0x1F) << 20
	b0 |= (uint64(reciever.F5) & 0x1F) << 25
	b0 |= (uint64(reciever.F6) & 0x1F) << 30
	b0 |= (uint64(reciever.F7) & 0x1F) << 35
	b0 |= (uint64(reciever.F8) & 0x1F) << 40
	b0 |= (uint64(reciever.F9) & 0x1F) << 45
	b0 |= (uint64(reciever.F10) & 0x1F) << 50
	b0 |= (uint64(reciever.F11) & 0x1F) << 55
	s0_12 := uint64(reciever.F12) & 0x7F
	b0 |= (s0_12 & 0xF) << 60
	binary.LittleEndian.PutUint64(bytes[index+0+0:index+0+8], uint64(b0))
	var b1 uint64
	b1 |= ((s0_12 >> 4) & 0x7)
	b1 |= (uint64(reciever.F13) & 0x1) << 3
	b1 |= (uint64(reciever.F14) & 0x1) << 4
	b1 |= (uint64(reciever.F15) & 0x1) << 5
	b1 |= (uint64(reciever.F16) & 0x1) << 6
	b1 |= (uint64(reciever.F17) & 0x3) << 7
	b1 |= (uint64(reciever.F18) & 0x1) << 9
	b1 |= (uint64(reciever.F19) & 0x1) << 10
	b1 |= (uint64(reciever.F20) & 0x3) << 11
	binary.LittleEndian.PutUint16(bytes[index+8+0:index+8+2], uint16(b1))
}

func (reciever *S) FromBytes(bytes []byte, index int) {
	var b0 uint64
	b0 |= uint64(bytes[index+0+0]) << 0
	b0 |= uint64(bytes[index+0+1]) << 8
	b0 |= uint64(bytes[index+0+2]) << 16
	b0 |= uint64(bytes[index+0+3]) << 24
	b0 |= uint64(bytes[index+0+4]) << 32
	b0 |= uint64(bytes[index+0+5]) << 40
	b0 |= uint64(bytes[index+0+6]) << 48
	b0 |= uint64(bytes[index+0+7]) << 56
	reciever.F0 = uint32(uint64((b0 >> 0) & 0x1F))
	reciever.F1 = uint32(uint64((b0 >> 5) & 0x1F))
	reciever.F2 = uint32(uint64((b0 >> 10) & 0x1F))
	reciever.F3 = uint32(uint64((b0 >> 15) & 0x1F))
	reciever.F4 = uint32(uint64((b0 >> 20) & 0x1F))
	reciever.F5 = uint32(uint64((b0 >> 25) & 0x1F))
	reciever.F6 = uint32(uint64((b0 >> 30) & 0x1F))
	reciever.F7 = uint32(uint64((b0 >> 35) & 0x1F))
	reciever.F8 = uint32(uint64((b0 >> 40) & 0x1F))
	reciever.F9 = uint32(uint64((b0 >> 45) & 0x1F))
	reciever.F10 = uint32(uint64((b0 >> 50) & 0x1F))
	reciever.F11 = uint32(uint64((b0 >> 55) & 0x1F))
	var b1 uint64
	b1 |= uint64(bytes[index+8+0]) << 0
	b1 |= uint64(bytes[index+8+1]) << 8
	s0_12 := ((b0 >> 60) & 0xF) | (((b1 >> 0) & 0x7) << 4)
	reciever.F12 = uint32(uint64(s0_12))
	reciever.F13 = uint32(uint64((b1 >> 3) & 0x1))
	reciever.F14 = uint32(uint64((b1 >> 4) & 0x1))
	reciever.F15 = uint32(uint64((b1 >> 5) & 0x1))
	reciever.F16 = uint32(uint64((b1 >> 6) & 0x1))
	reciever.F17 = uint32(uint64((b1 >> 7) & 0x3))
	reciever.F18 = uint32(uint64((b1 >> 9) & 0x1))
	reciever.F19 = uint32(uint64((b1 >> 10) & 0x1))
	reciever.F20 = uint32(uint64((b1 >> 11) & 0x3))
}

func (r *S) GetF0() int  { return int(r.F0) }
func (r *S) GetF1() int  { return int(r.F1) }
func (r *S) GetF2() int  { return int(r.F2) }
func (r *S) GetF3() int  { return int(r.F3) }
func (r *S) GetF4() int  { return int(r.F4) }
func (r *S) GetF5() int  { return int(r.F5) }
func (r *S) GetF6() int  { return int(r.F6) }
func (r *S) GetF7() int  { return int(r.F7) }
func (r *S) GetF8() int  { return int(r.F8) }
func (r *S) GetF9() int  { return int(r.F9) }
func (r *S) GetF10() int { return int(r.F10) }
func (r *S) GetF11() int { return int(r.F11) }
func (r *S) GetF12() int { return int(r.F12) }
func (r *S) GetF13() int { return int(r.F13) }
func (r *S) GetF14() int { return int(r.F14) }
func (r *S) GetF15() int { return int(r.F15) }
func (r *S) GetF16() int { return int(r.F16) }
func (r *S) GetF17() int { return int(r.F17) }
func (r *S) GetF18() int { return int(r.F18) }
func (r *S) GetF19() int { return int(r.F19) }
func (r *S) GetF20() int { return int(r.F20) }

type T struct {
	F0  uint32
	F1  uint32
	F2  uint32
	F3  uint32
	F4  uint32
	F5  uint32
	F6  uint32
	F7  uint32
	F8  uint32
	F9  uint32
	F10 uint32
	F11 uint32
	F12 uint32
	F13 uint32
	F14 uint32
	F15 uint32
	F16 uint32
	F17 uint32
	F18 uint32
	F19 uint32
	F20 uint32
}

func (reciever *T) Size() int {
	return 10
}

func (reciever *T) ToBytes(bytes []byte, index int) {
	var b0 uint64
	b0 |= (uint64(reciever.F0) & 0x1F) << 59
	b0 |= (uint64(reciever.F1) & 0x1F) << 54
	b0 |= (uint64(reciever.F2) & 0x1F) << 49
	b0 |= (uint64(reciever.F3) & 0x1F) << 44
	b0 |= (uint64(reciever.F4) & 0x1F) << 39
	b0 |= (uint64(reciever.F5) & 0x1F) << 34
	b0 |= (uint64(reciever.F6) & 0x1F) << 29
	b0 |= (uint64(reciever.F7) & 0x1F) << 24
	b0 |= (uint64(reciever.F8) & 0x1F) << 19
	b0 |= (uint64(reciever.F9) & 0x1F) << 14
	b0 |= (uint64(reciever.F10) & 0x1F) << 9
	b0 |= (uint64(reciever.F11) & 0x1F) << 4
	s0_12 := uint64(reciever.F12) & 0x7F
	b0 |= ((s0_12 >> 3) & 0xF)
	binary.BigEndian.PutUint64(bytes[index+0+0:index+0+8], uint64(b0))
	var b1 uint64
	b1 |= (s0_12 & 0x7) << 13
	b1 |= (uint64(reciever.F13) & 0x1) << 12
	b1 |= (uint64(reciever.F14) & 0x1) << 11
	b1 |= (uint64(reciever.F15) & 0x1) << 10
	b1 |= (uint64(reciever.F16) & 0x1) << 9
	b1 |= (uint64(reciever.F17) & 0x3) << 7
	b1 |= (uint64(reciever.F18) & 0x1) << 6
	b1 |= (uint64(reciever.F19) & 0x1) << 5
	b1 |= (uint64(reciever.F20) & 0x3) << 3
	binary.BigEndian.PutUint16(bytes[index+8+0:index+8+2], uint16(b1))
}

func (reciever *T) FromBytes(bytes []byte, index int) {
	var b0 uint64
	b0 |= uint64(bytes[index+0+7]) << 0
	b0 |= uint64(bytes[index+0+6]) << 8
	b0 |= uint64(bytes[index+0+5]) << 16
	b0 |= uint64(bytes[index+0+4]) << 24
	b0 |= uint64(bytes[index+0+3]) << 32
	b0 |= uint64(bytes[index+0+2]) << 40
	b0 |= uint64(bytes[index+0+1]) << 48
	b0 |= uint64(bytes[index+0+0]) << 56
	reciever.F0 = uint32(uint64((b0 >> 59) & 0x1F))
	reciever.F1 = uint32(uint64((b0 >> 54) & 0x1F))
	reciever.F2 = uint32(uint64((b0 >> 49) & 0x1F))
	reciever.F3 = uint32(uint64((b0 >> 44) & 0x1F))
	reciever.F4 = uint32(uint64((b0 >> 39) & 0x1F))
	reciever.F5 = uint32(uint64((b0 >> 34) & 0x1F))
	reciever.F6 = uint32(uint64((b0 >> 29) & 0x1F))
	reciever.F7 = uint32(uint64((b0 >> 24) & 0x1F))
	reciever.F8 = uint32(uint64((b0 >> 19) & 0x1F))
	reciever.F9 = uint32(uint64((b0 >> 14) & 0x1F))
	reciever.F10 = uint32(uint64((b0 >> 9) & 0x1F))
	reciever.F11 = uint32(uint64((b0 >> 4) & 0x1F))
	var b1 uint64
	b1 |= uint64(bytes[index+8+1]) << 0
	b1 |= uint64(bytes[index+8+0]) << 8
	s0_12 := (((b0 >> 0) & 0xF) << 3) | ((b1 >> 13) & 0x7)
	reciever.F12 = uint32(uint64(s0_12))
	reciever.F13 = uint32(uint64((b1 >> 12) & 0x1))
	reciever.F14 = uint32(uint64((b1 >> 11) & 0x1))
	reciever.F15 = uint32(uint64((b1 >> 10) & 0x1))
	reciever.F16 = uint32(uint64((b1 >> 9) & 0x1))
	reciever.F17 = uint32(uint64((b1 >> 7) & 0x3))
	reciever.F18 = uint32(uint64((b1 >> 6) & 0x1))
	reciever.F19 = uint32(uint64((b1 >> 5) & 0x1))
	reciever.F20 = uint32(uint64((b1 >> 3) & 0x3))
}

func (r *T) GetF0() int  { return int(r.F0) }
func (r *T) GetF1() int  { return int(r.F1) }
func (r *T) GetF2() int  { return int(r.F2) }
func (r *T) GetF3() int  { return int(r.F3) }
func (r *T) GetF4() int  { return int(r.F4) }
func (r *T) GetF5() int  { return int(r.F5) }
func (r *T) GetF6() int  { return int(r.F6) }
func (r *T) GetF7() int  { return int(r.F7) }
func (r *T) GetF8() int  { return int(r.F8) }
func (r *T) GetF9() int  { return int(r.F9) }
func (r *T) GetF10() int { return int(r.F10) }
func (r *T) GetF11() int { return int(r.F11) }
func (r *T) GetF12() int { return int(r.F12) }
func (r *T) GetF13() int { return int(r.F13) }
func (r *T) GetF14() int { return int(r.F14) }
func (r *T) GetF15() int { return int(r.F15) }
func (r *T) GetF16() int { return int(r.F16) }
func (r *T) GetF17() int { return int(r.F17) }
func (r *T) GetF18() int { return int(r.F18) }
func (r *T) GetF19() int { return int(r.F19) }
func (r *T) GetF20() int { return int(r.F20) }
